/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces_LJBD;

import DAO_LJBD.DAO_Distribuidora;
import Modelo_LJBD.Modelo_Distribuidora;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author eeuar
 */
public class Interface_Distribuidora extends javax.swing.JFrame {

    /**
     * Creates new form Interface_Distribuidora1
     */
    public Interface_Distribuidora() {
        initComponents();
    }
    public Interface_Distribuidora(Modelo_Distribuidora paraD) {
        initComponents();
        jTextNomeD.setText(paraD.getNomeD());
        jTextDataID.setText(paraD.getDataiD());
        jTextEmailD.setText(paraD.getEmailD());
        jCodigoD.setText(String.valueOf(paraD.getCodigoD()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAtu1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextNomeD = new javax.swing.JTextField();
        jTextDataID = new javax.swing.JTextField();
        jTextEmailD = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonCCD = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonVD = new javax.swing.JButton();
        jButtonBD = new javax.swing.JButton();
        jButtonAtuU = new javax.swing.JButton();
        jCodigoD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jButtonAtu1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButtonAtu1.setText("Atualizar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTextNomeD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeDActionPerformed(evt);
            }
        });

        jTextDataID = DD();
        jTextDataID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDataIDActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel5.setText("Data de Inclusão:");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel6.setText("Email:");

        jButtonCCD.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButtonCCD.setText("Criar Conta/Atualizar");
        jButtonCCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCCDActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel7.setText("Dados da Distribuidora");

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 8)); // NOI18N
        jLabel9.setText("*DD/MM/AAAA");

        jButtonVD.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButtonVD.setText("Voltar");
        jButtonVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVDActionPerformed(evt);
            }
        });

        jButtonBD.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButtonBD.setText("Buscar");
        jButtonBD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBDMouseEntered(evt);
            }
        });
        jButtonBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBDActionPerformed(evt);
            }
        });

        jButtonAtuU.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButtonAtuU.setText("Listar");
        jButtonAtuU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAtuUMouseEntered(evt);
            }
        });
        jButtonAtuU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtuUActionPerformed(evt);
            }
        });

        jCodigoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCodigoDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setText("Codigo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextNomeD, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextEmailD, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jButtonVD)
                            .addGap(70, 70, 70)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jButtonBD, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonAtuU, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jButtonCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(jTextDataID, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jCodigoD))))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextNomeD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextDataID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCodigoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(13, 13, 13)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextEmailD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCCD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBD)
                    .addComponent(jButtonAtuU)
                    .addComponent(jButtonVD))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       public JTextField DD (){
         try{

             javax.swing.text.MaskFormatter data = new javax.swing.text.MaskFormatter("##/##/####");

             return new javax.swing.JFormattedTextField(data);
         }
         catch(Exception e){
             JOptionPane.showMessageDialog(null, "Ocorreu um erro");

             return new JTextField();
         }
    }
    private void jTextNomeDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeDActionPerformed

    private void jTextDataIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDataIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDataIDActionPerformed

    private void jButtonCCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCCDActionPerformed
        // TODO add your handling code here:
        
        Modelo_Distribuidora InserirDistribuidora = new Modelo_Distribuidora();    
        InserirDistribuidora.setNomeD(jTextNomeD.getText());
        InserirDistribuidora.setDataiD(jTextDataID.getText());
        InserirDistribuidora.setEmailD(jTextEmailD.getText());
        if(jCodigoD.getText().trim().equalsIgnoreCase("")){
         InserirDistribuidora.setCodigoD(0);
        }else{
        InserirDistribuidora.setCodigoD(Integer.valueOf(jCodigoD.getText()));
        }
       
        
        DAO_Distribuidora DDAO = new DAO_Distribuidora();
        
        if(DDAO.ConsultaDI(String.valueOf(InserirDistribuidora.getCodigoD())) == null){
         if(DDAO.InserirDistribuidora(InserirDistribuidora)){
             JOptionPane.showMessageDialog(null, "A conta da distribuidora " + InserirDistribuidora.getNomeD() + " foi criada com sucesso.");
         }else{
              JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado ao criar a conta da distribuidora: " + InserirDistribuidora.getNomeD());
         }  
        }else{  
           if(DDAO.ATUD(InserirDistribuidora)){
                 JOptionPane.showMessageDialog(null, "A conta da distribuidora " + InserirDistribuidora.getNomeD() + " foi atualizada com sucesso.");
        }else{
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado ao atualizar a conta da distribuidora: " + InserirDistribuidora.getNomeD());
                } 
        }        
    }//GEN-LAST:event_jButtonCCDActionPerformed

    private void jButtonVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVDActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonVDActionPerformed

    private void jButtonBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBDActionPerformed
      Interface_ConsultaD DistribuidoraC = new Interface_ConsultaD();
       DistribuidoraC.setVisible(true);
        DistribuidoraC.jCodigoD.setEditable(false);
    }//GEN-LAST:event_jButtonBDActionPerformed

    private void jButtonAtuUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtuUActionPerformed
        Interface_ListagemD DistribuidoraLA = new Interface_ListagemD();
        DistribuidoraLA.setVisible(true);
    }//GEN-LAST:event_jButtonAtuUActionPerformed

    private void jCodigoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCodigoDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCodigoDActionPerformed

    private void jButtonBDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBDMouseEntered
        jButtonBD.setToolTipText("Clique aqui para buscar uma distribuidora ja cadastrada");
    }//GEN-LAST:event_jButtonBDMouseEntered

    private void jButtonAtuUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAtuUMouseEntered
        jButtonAtuU.setToolTipText("Clique aqui para listar as distribuidoras cadastradas");
    }//GEN-LAST:event_jButtonAtuUMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_Distribuidora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_Distribuidora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_Distribuidora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_Distribuidora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_Distribuidora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtu1;
    private javax.swing.JButton jButtonAtuU;
    private javax.swing.JButton jButtonBD;
    private javax.swing.JButton jButtonCCD;
    private javax.swing.JButton jButtonVD;
    public javax.swing.JTextField jCodigoD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextDataID;
    private javax.swing.JTextField jTextEmailD;
    private javax.swing.JTextField jTextNomeD;
    // End of variables declaration//GEN-END:variables
}
