
package Interfaces_LJBD;

import DAO_LJBD.DAO_Jogo;
import Modelo_LJBD.Modelo_Jogo;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author eeuar
 */
public class Interface_Jogo extends javax.swing.JFrame {

    /**
     * Creates new form Interface_Jogo1
     */
    public Interface_Jogo() {
        initComponents();
    }
    public Interface_Jogo(Modelo_Jogo paraJ) {
         initComponents();
         jTextNomeJ.setText(paraJ.getNomeJ());
         jTextDataJ.setText(paraJ.getDatalancJ());
         jTextFaixaeJ.setText(String.valueOf(paraJ.getFaixaeJ()));
         jTextGeneroJ.setText(paraJ.getGeneroJ());
         jTextIdiomasJ.setText(paraJ.getIdiomasJ());
         jTextRequisitosJ.setText(paraJ.getReqJ());
         jTextPrecoJ.setText(String.valueOf(paraJ.getPrecoJ()));
         jCodigoJ3.setText(String.valueOf(paraJ.getCodJ()));
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextNomeJ = new javax.swing.JTextField();
        jTextPrecoJ = new javax.swing.JTextField();
        jTextFaixaeJ = new javax.swing.JTextField();
        jTextGeneroJ = new javax.swing.JTextField();
        jTextDataJ = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonAJ = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextIdiomasJ = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextRequisitosJ = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jButtonVJ = new javax.swing.JButton();
        jButtonBJ = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jCodigoJ3 = new javax.swing.JTextField();
        jButtonAtuU = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTextNomeJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeJActionPerformed(evt);
            }
        });

        jTextPrecoJ= DTCeT(20, " 1234567890.,");

        jTextFaixaeJ = DTCeT(2, " 012345678");

        jTextGeneroJ = DTCeT(30, " abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZçÇéáíúóÁÉÓÍÚãõÃÕ");

        jTextDataJ = DD();
        jTextDataJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDataJActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setText("Nome: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setText("Preço");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setText("Faixa Etária:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setText("Gênero:");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel5.setText("Data de Lançamento:");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel6.setText("Idiomas:");

        jButtonAJ.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButtonAJ.setText("Adicionar Jogo/Atualizar");
        jButtonAJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAJActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel7.setText("Dados do Jogo");

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel8.setText("Requistos:");

        jTextIdiomasJ.setColumns(20);
        jTextIdiomasJ.setRows(5);
        jScrollPane1.setViewportView(jTextIdiomasJ);

        jTextRequisitosJ.setColumns(20);
        jTextRequisitosJ.setRows(5);
        jScrollPane2.setViewportView(jTextRequisitosJ);

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 8)); // NOI18N
        jLabel9.setText("*DD/MM/AAAA");

        jButtonVJ.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButtonVJ.setText("Voltar");
        jButtonVJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVJActionPerformed(evt);
            }
        });

        jButtonBJ.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButtonBJ.setText("Buscar");
        jButtonBJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBJMouseEntered(evt);
            }
        });
        jButtonBJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBJActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel33.setText("Codigo:");

        jButtonAtuU.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButtonAtuU.setText("Listar");
        jButtonAtuU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAtuUMouseEntered(evt);
            }
        });
        jButtonAtuU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtuUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel33)
                        .addComponent(jTextNomeJ)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(jLabel6)
                                .addComponent(jLabel2)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFaixaeJ)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextPrecoJ))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(jTextDataJ)
                                .addComponent(jTextGeneroJ)))
                        .addComponent(jScrollPane1)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButtonVJ)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                            .addComponent(jButtonBJ, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonAtuU, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jCodigoJ3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButtonAJ, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextNomeJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPrecoJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDataJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFaixaeJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextGeneroJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCodigoJ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBJ)
                    .addComponent(jButtonVJ)
                    .addComponent(jButtonAtuU))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

      public JTextField DTCeT(int Tam, String cara){
        try{
            String QT = "";
                for (int i = 0; i < Tam; i++){
                    QT = QT + "*";
                }
         javax.swing.text.MaskFormatter Area = new javax.swing.text.MaskFormatter(QT);
            Area.setValidCharacters(cara);
                return new javax.swing.JFormattedTextField(Area);                            
        } 
    
        catch (Exception e){
                JOptionPane.showMessageDialog(null, "Houve um erro");
                    return new  JTextField();
        }
    }
      public JTextField DD (){
         try{

             javax.swing.text.MaskFormatter data = new javax.swing.text.MaskFormatter("##/##/####");

             return new javax.swing.JFormattedTextField(data);
         }
         catch(Exception e){
             JOptionPane.showMessageDialog(null, "Ocorreu um erro");

             return new JTextField();
         }
    }
    private void jTextNomeJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeJActionPerformed

    private void jTextDataJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDataJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDataJActionPerformed

    private void jButtonAJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAJActionPerformed
        // TODO add your handling code here:
        
        Modelo_Jogo InserirJogo = new Modelo_Jogo();
        InserirJogo.setNomeJ(jTextNomeJ.getText());
        InserirJogo.setPrecoJ(Double.valueOf(jTextPrecoJ.getText()));
        InserirJogo.setFaixaeJ(Integer.valueOf(jTextFaixaeJ.getText()));
        InserirJogo.setDatalancJ(jTextDataJ.getText());
        InserirJogo.setGeneroJ(jTextGeneroJ.getText());
        InserirJogo.setIdiomasJ(jTextIdiomasJ.getText());
        InserirJogo.setReqJ(jTextRequisitosJ.getText());
       
        if(jCodigoJ3.getText().trim().equalsIgnoreCase("")){
         InserirJogo.setCodJ(0);
        }else{
        InserirJogo.setCodJ(Integer.valueOf(jCodigoJ3.getText()));
        }
     
        
        DAO_Jogo JDAO = new DAO_Jogo();
        if (JDAO.ConsultaJO(String.valueOf(InserirJogo.getCodJ())) == null){
            if(JDAO.InserirJogo(InserirJogo)){
                 JOptionPane.showMessageDialog(null, "O Jogo " + InserirJogo.getNomeJ() + " foi inserido com sucesso no nosso sistema.");
        }else{
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado ao tentar adicionar o Jogo " + InserirJogo.getNomeJ() + " no nosso sistema.");
                }
        }else{  
           if(JDAO.ATUJ(InserirJogo)){
                 JOptionPane.showMessageDialog(null, "Os dados do Jogo " + InserirJogo.getNomeJ() + " foram atualizados com sucesso.");
        }else{
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado ao tentar atualizar o Jogo: " + InserirJogo.getNomeJ());
                } 
        }
    }//GEN-LAST:event_jButtonAJActionPerformed

    private void jButtonVJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVJActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonVJActionPerformed

    private void jButtonBJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBJActionPerformed
        Interface_ConsultaJ JogoC = new Interface_ConsultaJ();
        JogoC.setVisible(true);
        JogoC.jCodigoJ.setEditable(false);
    }//GEN-LAST:event_jButtonBJActionPerformed

    private void jButtonAtuUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtuUActionPerformed
        Interface_ListagemJ JogoLA = new Interface_ListagemJ();
        JogoLA.setVisible(true);
    }//GEN-LAST:event_jButtonAtuUActionPerformed

    private void jButtonBJMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBJMouseEntered
          jButtonBJ.setToolTipText("Clique aqui para buscar um jogo cadastrado");
    }//GEN-LAST:event_jButtonBJMouseEntered

    private void jButtonAtuUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAtuUMouseEntered
            jButtonAtuU.setToolTipText("Clique aqui para listar os jogos cadastrados");
    }//GEN-LAST:event_jButtonAtuUMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_Jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAJ;
    private javax.swing.JButton jButtonAtuU;
    private javax.swing.JButton jButtonBJ;
    private javax.swing.JButton jButtonVJ;
    public javax.swing.JTextField jCodigoJ3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextDataJ;
    private javax.swing.JTextField jTextFaixaeJ;
    private javax.swing.JTextField jTextGeneroJ;
    private javax.swing.JTextArea jTextIdiomasJ;
    private javax.swing.JTextField jTextNomeJ;
    private javax.swing.JTextField jTextPrecoJ;
    private javax.swing.JTextArea jTextRequisitosJ;
    // End of variables declaration//GEN-END:variables
}
